# Generated by Django 4.0.3 on 2022-03-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='action',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
