# Generated by Django 4.0.3 on 2022-03-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_alter_habit_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='one_record_per_day',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('date', 'record'), name='one_record_per_day'),
        ),
    ]
