# Generated by Django 4.0.3 on 2022-03-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_remove_record_one_record_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='one_record_per_day',
        ),
        migrations.AddField(
            model_name='record',
            name='units',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('record', 'units'), name='one_record_per_day'),
        ),
    ]
