# Generated by Django 4.0.3 on 2022-03-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0009_remove_record_one_record_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='one_record_per_day',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='one_record_per_day'),
        ),
    ]
